## Oreomeow
## github地址   https://github.com/Oreomeow/QuantumultX.git

## 作者名         Oreomeow
## 作者库名       QuantumultX
## 作者分支名     master
## 同步分支名     Oreomeow-QuantumultX

name: Oreomeow-sngxQX-sync
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Oreomeow-QuantumultX
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false


      - name: sync Oreomeow-QuantumultX
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Oreomeow/QuantumultX.git"
          source_branch: "master"
          destination_branch: "Oreomeow-QuantumultX"
          github_token: ${{ secrets.PAT }}
