name: zero205_JD-sync
on:
  schedule:
    - cron: '9 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-zero205-JD
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync zero205-JD
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/zero205/JD.git"
          source_branch: "main"
          destination_branch: "zero205_JD"
          github_token: ${{ secrets.PAT }}
